# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayinthelifeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='choices',
        ),
        migrations.AddField(
            model_name='student',
            name='choices',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
