# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayinthelifeapp', '0002_auto_20161214_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='choices',
            field=models.CharField(default='', max_length=255),
        ),
    ]
